name: Deploy to Netlify

on:
  push:
    branches:
      - master  # o 'main' si usas esa rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
<<<<<<< HEAD
      # Paso 1: Checkout del c贸digo
=======
<<<<<<< HEAD
      # Paso 1: Checkout del c贸digo
=======
      # Paso 1: Hacer checkout del c贸digo del repositorio
>>>>>>> 5e02dbcfa5b679c2cc840dffab7ab6125e960da9
>>>>>>> 795dc8c1a3f05dfa8c67a4d1790f6c722a8df9f7
      - name: Checkout code
        uses: actions/checkout@v2

      # Paso 2: Configurar Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'  # O la versi贸n que prefieras

      # Paso 3: Instalar dependencias
      - name: Install dependencies
        run: npm install

      # Paso 4: Descargar e instalar Netlify CLI
      - name: Download and install Netlify CLI
        run: |
          curl -sL https://github.com/netlify/cli/releases/download/v6.0.0/netlify-cli-linux-x64.tar.gz -o netlify-cli.tar.gz
          tar -xzf netlify-cli.tar.gz
          sudo mv netlify-cli /usr/local/bin/

      # Paso 5: Desplegar en Netlify
      - name: Deploy to Netlify
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}  # Tu variable de entorno de MongoDB
        run: |
<<<<<<< HEAD
          netlify deploy --prod
=======
<<<<<<< HEAD
          netlify deploy --prod
=======
          ./netlify deploy --prod
>>>>>>> 5e02dbcfa5b679c2cc840dffab7ab6125e960da9
>>>>>>> 795dc8c1a3f05dfa8c67a4d1790f6c722a8df9f7
